FROM php:5.6-apache
# Install XDebug
RUN yes | pecl install xdebug \
    && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/xdebug.ini

# Install PHP exrensions.
RUN apt-get update \
    	&& apt-get install -y \
    		imagemagick \
    		graphicsmagick \
    		zip \
    		unzip \
    		wget \
    		curl \
    		git \
    		mysql-client \
    		moreutils \
    		dnsutils \
        && docker-php-ext-install -j$(nproc) mysqli \
    	&& rm -rf /var/lib/apt/lists/*
# Enable mod_rewrite.
RUN a2enmod deflate filter rewrite headers

# Enable mod_expires
RUN cp /etc/apache2/mods-available/expires.load /etc/apache2/mods-enabled/

# Copy PHP configuration file template.
COPY php.ini /usr/local/etc/php